### PR TITLE
Add ALBA endpoint to providers list

### PR DESCRIPTION
**Pull request by leRoderic**
Added ALBA's Search API endpoint to the providers list

### CODE REVIEW

**Comment by nitrosx** [comment]
I just tried the following filter:
```
query: electron
```
which is implemented with the following curl command:
```bash
curl -X GET --header 'Accept: application/json' 'https://data.cells.es/iws/panosc/search-api/Documents?filter=%7B%22query%22%20%3A%20%22electron%22%7D'
```
and I received the following response
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
```

**Comment by nitrosx** [comment]
When I send a request with no filters to the documents endpoint I receive two entries, but with no score:
```
curl -X GET --header 'Accept: application/json' 'https://data.cells.es/iws/panosc/search-api/Documents' | jq .
[
  {
    "pid": "2018129999",
    "isPublic": true,
    "type": "SAXS",
    "title": "ICAT Tests BL11",
    "summary": "ICAT Tests BL11",
    "doi": "10.57710/ALBA-ES-11",
    "startDate": "2018-12-21T10:53:46.000Z",
    "endDate": "2019-04-08T12:31:19.000Z",
    "releaseDate": "9999-12-24T01:53:47.000Z",
    "license": null,
    "keywords": [],
    "datasets": [],
    "members": [],
    "parameters": []
  },
  {
    "pid": "2023097869",
    "isPublic": true,
    "type": "ARPES",
    "title": "Electron doping effects on the metal-insulator transition in perovskite nickelates: the case of NdNiO3",
    "summary": "The rich experimental phenomenology of rare earth perovskite nickelates has recently\nattracted considerable attention, particularly because of interest in the physics of phase transitions in correlated oxides where electron-lattice coupling is essential. Nickelates exhibit a metal-insulator transition (MIT), peculiar magnetic behaviour, lattice distortions, charge ordering and the potential for additional carrier injection and lattice distortion by dopants. Substitutional doping has been used as a common method for electron doping. The resulting changes are still not fully understood and the exact mechanisms that drive the MIT are still under debate, as dopants also introduce lattice distortions. Our main aim is to investigate the effects of pure electron doping in single crystalline epitaxial NdNiO3, where Li doping is used as the electron source. Our research will shed light on the spectral origin of the occupied states and the physical source of MIT suppression. In particular, we will test the accuracy of the negative charge transfer description and identify the electronic states\nobserved for both the metallic and insulating phases.",
    "doi": "10.57710/ALBA-ES-422",
    "startDate": "2024-01-28T06:00:00.000Z",
    "endDate": "2024-01-28T22:00:00.000Z",
    "releaseDate": "2027-01-28T22:00:00.000Z",
    "license": null,
    "keywords": [],
    "datasets": [],
    "members": [],
    "parameters": []
  }
]
```

**Comment by nitrosx** [comment]
The following request with hard filters works correctly:
```
where : 
  title:
    like: Electron
```
 

```
url -X GET --header 'Accept: application/json' 'https://data.cells.es/iws/panosc/search-api/Documents?filter=%7B%22where%22%3A%7B%22title%22%3A%7B%22like%22%20%3A%20%22Electron%22%7D%7D%7D' | jq .

[
  {
    "pid": "2023097869",
    "isPublic": true,
    "type": "ARPES",
    "title": "Electron doping effects on the metal-insulator transition in perovskite nickelates: the case of NdNiO3",
    "summary": "The rich experimental phenomenology of rare earth perovskite nickelates has recently\nattracted considerable attention, particularly because of interest in the physics of phase transitions in correlated oxides where electron-lattice coupling is essential. Nickelates exhibit a metal-insulator transition (MIT), peculiar magnetic behaviour, lattice distortions, charge ordering and the potential for additional carrier injection and lattice distortion by dopants. Substitutional doping has been used as a common method for electron doping. The resulting changes are still not fully understood and the exact mechanisms that drive the MIT are still under debate, as dopants also introduce lattice distortions. Our main aim is to investigate the effects of pure electron doping in single crystalline epitaxial NdNiO3, where Li doping is used as the electron source. Our research will shed light on the spectral origin of the occupied states and the physical source of MIT suppression. In particular, we will test the accuracy of the negative charge transfer description and identify the electronic states\nobserved for both the metallic and insulating phases.",
    "doi": "10.57710/ALBA-ES-422",
    "startDate": "2024-01-28T06:00:00.000Z",
    "endDate": "2024-01-28T22:00:00.000Z",
    "releaseDate": "2027-01-28T22:00:00.000Z",
    "license": null,
    "keywords": [],
    "datasets": [],
    "members": [],
    "parameters": []
  }
]
```

**Comment by nitrosx** [comment]
```

**Review by nitrosx — CHANGES_REQUESTED** [review]
Please check my comments and let me know.
Use data.panosc.eu as a reference of how the filters are built and passed to the institution panosc search api

**Comment by leRoderic** [comment]
Adjusted conflicting rule that was forbidding API requests. Both endpoints are now available with no restriction and with score returned with the query filter.

**Comment by nitrosx** [comment]
Now the three queries work fine.
1) 
```
curl -X GET --header 'Accept: application/json' 'https://data.cells.es/iws/panosc/search-api/Documents' | jq .
```
Results
```
[
  {
    "pid": "2018129999",
    "isPublic": true,
    "type": "SAXS",
    "title": "ICAT Tests BL11",
    "summary": "ICAT Tests BL11",
    "doi": "10.57710/ALBA-ES-11",
    "startDate": "2018-12-21T10:53:46.000Z",
    "endDate": "2019-04-08T12:31:19.000Z",
    "releaseDate": "9999-12-24T01:53:47.000Z",
    "license": null,
    "keywords": [],
    "datasets": [],
    "members": [],
    "parameters": []
  },
  {
    "pid": "2023097869",
    "isPublic": true,
    "type": "ARPES",
    "title": "Electron doping effects on the metal-insulator transition in perovskite nickelates: the case of NdNiO3",
    "summary": "The rich experimental phenomenology of rare earth perovskite nickelates has recently\nattracted considerable attention, particularly because of interest in the physics of phase transitions in correlated oxides where electron-lattice coupling is essential. Nickelates exhibit a metal-insulator transition (MIT), peculiar magnetic behaviour, lattice distortions, charge ordering and the potential for additional carrier injection and lattice distortion by dopants. Substitutional doping has been used as a common method for electron doping. The resulting changes are still not fully understood and the exact mechanisms that drive the MIT are still under debate, as dopants also introduce lattice distortions. Our main aim is to investigate the effects of pure electron doping in single crystalline epitaxial NdNiO3, where Li doping is used as the electron source. Our research will shed light on the spectral origin of the occupied states and the physical source of MIT suppression. In particular, we will test the accuracy of the negative charge transfer description and identify the electronic states\nobserved for both the metallic and insulating phases.",
    "doi": "10.57710/ALBA-ES-422",
    "startDate": "2024-01-28T06:00:00.000Z",
    "endDate": "2024-01-28T22:00:00.000Z",
    "releaseDate": "2027-01-28T22:00:00.000Z",
    "license": null,
    "keywords": [],
    "datasets": [],
    "members": [],
    "parameters": []
  }
]
```
2)
```
curl -X GET --header 'Accept: application/json' 'https://data.cells.es/iws/panosc/search-api/Documents?filter=%7B%22where%22%3A%7B%22title%22%3A%7B%22like%22%20%3A%20%22Electron%22%7D%7D%7D' | jq .
```
Results
```
[
  {
    "pid": "2023097869",
    "isPublic": true,
    "type": "ARPES",
    "title": "Electron doping effects on the metal-insulator transition in perovskite nickelates: the case of NdNiO3",
    "summary": "The rich experimental phenomenology of rare earth perovskite nickelates has recently\nattracted considerable attention, particularly because of interest in the physics of phase transitions in correlated oxides where electron-lattice coupling is essential. Nickelates exhibit a metal-insulator transition (MIT), peculiar magnetic behaviour, lattice distortions, charge ordering and the potential for additional carrier injection and lattice distortion by dopants. Substitutional doping has been used as a common method for electron doping. The resulting changes are still not fully understood and the exact mechanisms that drive the MIT are still under debate, as dopants also introduce lattice distortions. Our main aim is to investigate the effects of pure electron doping in single crystalline epitaxial NdNiO3, where Li doping is used as the electron source. Our research will shed light on the spectral origin of the occupied states and the physical source of MIT suppression. In particular, we will test the accuracy of the negative charge transfer description and identify the electronic states\nobserved for both the metallic and insulating phases.",
    "doi": "10.57710/ALBA-ES-422",
    "startDate": "2024-01-28T06:00:00.000Z",
    "endDate": "2024-01-28T22:00:00.000Z",
    "releaseDate": "2027-01-28T22:00:00.000Z",
    "license": null,
    "keywords": [],
    "datasets": [],
    "members": [],
    "parameters": []
  }
]
```
3) 
```
curl -X GET --header 'Accept: application/json' 'https://data.cells.es/iws/panosc/search-api/Documents?filter=%7B%22query%22%20%3A%20%22electron%22%7D' | jq .
```
Results
```
[
  {
    "pid": "2023097869",
    "isPublic": true,
    "type": "ARPES",
    "title": "Electron doping effects on the metal-insulator transition in perovskite nickelates: the case of NdNiO3",
    "summary": "The rich experimental phenomenology of rare earth perovskite nickelates has recently\nattracted considerable attention, particularly because of interest in the physics of phase transitions in correlated oxides where electron-lattice coupling is essential. Nickelates exhibit a metal-insulator transition (MIT), peculiar magnetic behaviour, lattice distortions, charge ordering and the potential for additional carrier injection and lattice distortion by dopants. Substitutional doping has been used as a common method for electron doping. The resulting changes are still not fully understood and the exact mechanisms that drive the MIT are still under debate, as dopants also introduce lattice distortions. Our main aim is to investigate the effects of pure electron doping in single crystalline epitaxial NdNiO3, where Li doping is used as the electron source. Our research will shed light on the spectral origin of the occupied states and the physical source of MIT suppression. In particular, we will test the accuracy of the negative charge transfer description and identify the electronic states\nobserved for both the metallic and insulating phases.",
    "doi": "10.57710/ALBA-ES-422",
    "startDate": "2024-01-28T06:00:00.000Z",
    "endDate": "2024-01-28T22:00:00.000Z",
    "releaseDate": "2027-01-28T22:00:00.000Z",
    "license": null,
    "keywords": [],
    "datasets": [],
    "members": [],
    "parameters": [],
    "score": -1
  }
]
```

**Comment by nitrosx** [comment]
Just one comment: the score when the query filter is used is set to -1.
Scores outside the interval 0 and 1 are discarded automatically.

I will go ahead and include your endpoint, but I suggest to set the score to 0 if not to a real value.

**Review by nitrosx — APPROVED** [review]

**Comment by andygotz** [comment]
Thanks Max! Can we add ALBA to the list of sites on the home page? Who can do this and deploy the new version- you or should I ask Axel?

**Comment by nitrosx** [comment]
I will let you know tomorrow.
Let me check if i remember how to do it.

Max

Sent from my iPhone

On 31 Jan 2024, at 16:51, Andy Gotz ***@***.***> wrote:

﻿

Thanks Max! Can we add ALBA to the list of sites on the home page? Who can do this and deploy the new version- you or should I ask Axel?

**Comment by nitrosx** [comment]
@leRoderic and @andygotz 
ALBA now is officially a data provider for the PaNOSC data portal. It is also listed on https://data.panosc.eu.

**Pull request merged**
